### ISSUE TITLE
Pyenv Activate Fails

### ISSUE THREAD

**Issue by DustinMoriarty** [pyenv/pyenv-virtualenv#391]
I have recently encountered pyenv-activate failing with the following error on a machine which previously did not show this error. 

```bash
$ pyenv activate devenv

Failed to activate virtualenv.

Perhaps pyenv-virtualenv has not been loaded into your shell properly.
Please restart current shell and try again.
```

OS: Fedora 33
Pyenv Version: pyenv 2.0.0
Pyenv Virtualenv Commit: 6742d0ef108450ca607ca9db7007c4a84db06531 (It appears that the pyenv installer just pulls master instead of the latest release)

My `~/.bashrc` contains the following.
```bash
# User specific aliases and functions
export PYENV_ROOT=$HOME/.pyenv
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv virtualenv-init -)"
```

I tried sourcing the `~/.bashrc` separately as well as running these commands independently.

The installation uses ansible, so the ansible playbook may be useful if anyone wants to reproduce the exact configuration on Fedora.

```yaml
- name: install pyenv
  hosts: all
  vars:
    user: vagrant
    pyenv_tmp_dir: /home/{{ user|mandatory}}/pyenv_install
    pyenv_root: "/home/{{ user|mandatory}}/.pyenv"
    pyenv_executable: "{{ pyenv_root }}/bin/pyenv"
  tasks:
    - name: Install pyenv dendencies
      yum:
        name:
          - "@Development Tools"
          - libffi-devel 
          - zlib-devel 
          - bzip2-devel 
          - readline-devel 
          - sqlite-devel 
          - wget 
          - curl 
          - llvm 
          - ncurses-devel 
          - openssl-devel 
          - lzma-sdk-devel 
          - libyaml-devel 
        state: latest
      become: yes
    - name: Make checkout directory
      file:
        path: "{{ pyenv_tmp_dir }}"
        state: directory
    - name: Get pyenv source
      get_url:
        url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
        dest: "{{ pyenv_tmp_dir }}"
        mode: 0755
    - name: Run pyenv installer
      command: "{{ pyenv_tmp_dir|quote }}/pyenv-installer"
      args:
        creates: "{{ pyenv_root }}"
      become_user: "{{ user|mandatory }}"
      become: yes
    - name: Clean up
      file:
        path: "{{ pyenv_tmp_dir }}"
        state: absent
    - name: set pyenv home.
      lineinfile:
        line: export PYENV_ROOT=$HOME/.pyenv
        path: /home/{{ user|mandatory }}/.bashrc
        state: present
    - name: Add pyenv to path for user.
      lineinfile:
        line: export PATH="$PYENV_ROOT/bin:$PATH"
        path: "/home/{{ user|mandatory }}/.bashrc"
        state: present
    - name: Remove old pyenv init to bashrc
      lineinfile:
        line: eval "$(pyenv init -)"
        path: "/home/{{ user|mandatory }}/.bashrc"
        state: absent
    - name: Add pyenv init to bashrc
      lineinfile:
        line: eval "$(pyenv init --path)"
        path: "/home/{{ user|mandatory }}/.bashrc"
        state: present
    - name: Add pyenv virtualenv init to bashrc
      lineinfile:
        line: eval "$(pyenv virtualenv-init -)"
        path: "/home/{{ user|mandatory }}/.bashrc"
        state: present
    - name: Install python 3.6
      command: "{{ pyenv_executable }} install 3.6.11"
      args:
        creates: "{{ pyenv_root }}/versions/3.6.11"
      become_user: "{{ user|mandatory }}"
      become: yes
    - name: Install python 3.7
      command: "{{ pyenv_executable }} install 3.7.8"
      args:
        creates: "{{ pyenv_root }}/versions/3.7.8"
      become_user: "{{ user|mandatory }}"
      become: yes
    - name: Install python 3.8
      command: "{{ pyenv_executable }} install 3.8.6"
      args:
        creates: "{{ pyenv_root }}/versions/3.8.6"
      become_user: "{{ user|mandatory }}"
      become: yes
    - name: Install python 3.9
      command: "{{ pyenv_executable }} install 3.9.2"
      args:
        creates: "{{ pyenv_root }}/versions/3.9.2"
      become_user: "{{ user|mandatory }}"
      become: yes
    - name: Declare python 3.8 as global
      command: "{{ pyenv_executable }} global 3.9.2"
      become_user: "{{ user|mandatory }}"
      become: yes
```
